[project]
name = "symbchainsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "mkdocs-material>=9.6.20",
    "numpy>=2.3.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]

[tool.ruff]
line-length = 200 
target-version = "py313"

[tool.ruff.format]
quote-style = "double" 
indent-style = "space" 
skip-magic-trailing-comma = false
