dynamic_sim:
  use: False
  config: "Configs/dynamic_config.yaml"

simulation:
  init_CP: "PBFT"
  simTime: -1
  stop_after_blocks: 100
  interval_switch: False
  interval_mean: 30
  debugging_mode: False
  remove_timeouts: True
  print_every: -1
  snapshots: False
  print_info: False

application:
  Nn: 16
  TI_dur: 25
  Tn: 400
  base_transation_size: 0
  Tsize: 0.05
  transaction_model: "local"

execution:
  creation_time: 0.1
  block_val_delay: 0.025
  msg_val_delay: 0.01
  sync_message_request_delay: 1
  proposer_selection: "round_robin"

data:
  Bsize: 5
  base_block_size: 0
  block_interval: 0

network:
  base_msg_size: 0.2
  gossip: False
  num_neighbours: 3
  use_latency: local
  same_city_latency_ms: 10
  same_city_dev_ms: 0
  queueing_delay: 0
  processing_delay: 0

  bandwidth:
    mean: 100
    dev: 0
    min: 2

  measure_avg_transmission_delay: False

consensus:
  BigFoot: Chain/Consensus/BigFoot/BigFoot_config.yaml
  PBFT: Chain/Consensus/PBFT/PBFT_config.yaml

behaviour:
  use: False
  config: "Configs/behaviour_config.yaml"
