simulation:
  init_CP: "PBFT"
  simTime: 600
  stop_after_blocks: -1
  interval_switch: False
  interval_mean: 30
  debugging_mode: True
  remove_timeouts: True

application:
  Nn: 4
  TI_dur: 25
  Tn: 30
  Tsize: 0.01
  transaction_model: "global"

execution:
  creation_time: 0.05
  block_val_delay: 0.025
  msg_val_delay: 0.01
  sync_message_request_delay: 1
  proposer_selection: "round_robin"

data:
  Bsize: 1
  base_block_size: 0
  block_interval: 0

network:
  base_msg_size: 0.2
  gossip: False
  num_neighbours: 2
  use_latency: measured
  same_city_latency_ms: 10
  same_city_dev_ms: 5
  queueing_delay: 0
  processing_delay: 0

  bandwidth:
    mean: 10_000
    dev: 0
    debug: False

consensus:
  BigFoot: Chain/Consensus/BigFoot/BigFoot_config.yaml
  PBFT: Chain/Consensus/PBFT/PBFT_config.yaml

behaviour:
  behaviour_interval: 10

  byzantine_nodes:
    # percent of nodes that will be byzantine
    # (percentange based on how many faulty nodes the network can tolerate)
    num_byzantine: 0
  sync:
    # define the chance a byzantine node will send bad sync data
    # (and the delay that will cause)
    bad_data:
      delay: 10
    # define the chance a byzantine node will not responde to a sync message
    # (and the delay that will cause)
    no_response:
      delay: 5
    probs:
      low: 5
      high: 20

  crash_probs:
    # percent of nodes that can crash (go offiline)
    faulty_nodes: 0
    # probabilities for crash
    mean_fault_time:
      low: 30
      high: 60
    # how long for the node to recover
    mean_recovery_time:
      low: 10
      high: 60
