byzantine:
  # number of byzantine nodes
  num: 0
  sync:
    # define the chance a byzantine node will send bad sync data (and the delay that will cause)
    bad_data:
      delay: 10
    # define the chance a byzantine node will not respond to a sync message (and the delay that will cause)
    no_response:
      delay: 5
    probs: [5, 20]

faulty:
  # number of faulty nodes
  num: 2
  # probabilities for crash
  mean_fault_range: [100, 150]
  # how long for the node to recover
  mean_recovery_range: [50, 100]
