byzantine:
  # percent of nodes that will be byzantine
  # (percentage based on how many faulty nodes the network can tolerate)
  num: 0
  sync:
    # define the chance a byzantine node will send bad sync data
    # (and the delay that will cause)
    bad_data:
      delay: 10
    # define the chance a byzantine node will not respond to a sync message
    # (and the delay that will cause)
    no_response:
      delay: 5
    probs: [5, 20]

faulty:
  # percent of nodes that can crash (go offline)
  num: 5
  # probabilities for crash
  mean_fault_range: [60, 120]
  # how long for the node to recover
  mean_recovery_range: [10, 50]
