dynamic_sim:
  use: False
  config: "Configs/dynamic_config.yaml"

simulation:
  init_CP: "PBFT"
  simTime: -1
  stop_after_blocks: 100
  interval_switch: False
  interval_mean: 30
  interval_sigma: 2
  debugging_mode: False
  remove_timeouts: False
  print_every: 50
  snapshots: False
  print_info: False

application:
  Nn: 8 # replaced by profiler script
  TI_dur: 25
  Tn: 400 # replaced by profiler script
  base_transaction_size: 0
  Tsize: 0.01
  transaction_model: "local" # replaced by profiler script
  use_tx_prop_model: True # only when tx_model: global

execution:
  creation_time: 0.1
  block_val_delay: 0.025
  msg_val_delay: 0.01
  sync_message_request_delay: 1
  proposer_selection: "round_robin"

data:
  Bsize: 1
  base_block_size: 0
  block_interval: 0

network:
  base_msg_size: 0.2
  gossip: False
  num_neighbours: 3
  use_latency: "local"
  same_city_latency_ms: 10
  same_city_dev_ms: 0
  queueing_delay: 0
  processing_delay: 0

  bandwidth:
    mean: 10
    dev: 3
    min: 2

  measure_avg_transmission_delay: False

consensus:
  BigFoot: Chain/Consensus/BigFoot/BigFoot_config.yaml
  PBFT: Chain/Consensus/PBFT/PBFT_config.yaml

behaviour:
  use: False
  config: "Configs/behaviour_config.yaml"
