simulation:
  init_CP: "BigFoot"

  interval_switch: False
  interval_mean: 60
  interval_sigma: 10

  debugging_mode: False
  remove_timeouts: False

  print_every: 100
  snapshot_interval: 30

  print_info: False

  simulate_faults: False

application:
  transaction_model: "local"

execution:
  creation_time: 0.1
  block_val_delay: 0.025
  msg_val_delay: 0.01
  sync_message_request_delay: 1
  proposer_selection: "round_robin"

data:
  Bsize: 10
  base_block_size: 0
  block_interval: 0

network:
  base_msg_size: 0.2
  gossip: False
  num_neighbours: 3
  use_latency: "off"
  same_city_latency_ms: 10
  same_city_dev_ms: 0
  queueing_delay: 0
  processing_delay: 0

  measure_avg_transmission_delay: False

consensus:
  BigFoot: Chain/Consensus/BigFoot/BigFoot_config.yaml
  PBFT: Chain/Consensus/PBFT/PBFT_config.yaml
  Tendermint: Chain/Consensus/Tendermint/TM_config.yaml
